### ISSUE TITLE
Bottom player box not working on Galaxy S9+ 

### ISSUE THREAD

**Issue by phuongphally** [boyan01/quiet-flutter#9]
Last version work. But current version not work.

**Comment by boyan01** [comment]
is any log output？

**Comment by phuongphally** [comment]
Don't have any error.

**Comment by phuongphally** [comment]
````
I/QuietPlayerChannel( 5024): (QuietPlayerChannel.kt:92)QuietPlayerChannel.onMethodCall: call : playWithPlaylist
I/QuietMusicPlayer( 5024): (QuietMusicPlayer.kt:101)QuietMusicPlayer.play: try to play {id : 409931583 , title : Snakes (Extended Mix)}
D/QuietPlayerService$Companion( 5024): (QuietPlayerService.kt:85)QuietPlayerService$Companion.ensureServiceRunning$default: we do not need to start music MusicPlayer service ,because it is already running...
E/ExoPlayerImplInternal( 5024): Source error.
E/ExoPlayerImplInternal( 5024): com.google.android.exoplayer2.upstream.HttpDataSource$InvalidResponseCodeException: Response code: 302
E/ExoPlayerImplInternal( 5024): 	at com.google.android.exoplayer2.upstream.DefaultHttpDataSource.open(DefaultHttpDataSource.java:300)
E/ExoPlayerImplInternal( 5024): 	at com.google.android.exoplayer2.upstream.DefaultDataSource.open(DefaultDataSource.java:250)
E/ExoPlayerImplInternal( 5024): 	at com.google.android.exoplayer2.upstream.TeeDataSource.open(TeeDataSource.java:53)
E/ExoPlayerImplInternal( 5024): 	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.openNextSource(CacheDataSource.java:479)
E/ExoPlayerImplInternal( 5024): 	at com.google.android.exoplayer2.upstream.cache.CacheDataSource.open(CacheDataSource.java:308)
E/ExoPlayerImplInternal( 5024): 	at com.google.android.exoplayer2.upstream.StatsDataSource.open(StatsDataSource.java:83)
E/ExoPlayerImplInternal( 5024): 	at com.google.android.exoplayer2.source.ExtractorMediaPeriod$ExtractingLoadable.load(ExtractorMediaPeriod.java:885)
E/ExoPlayerImplInternal( 5024): 	at com.google.android.exoplayer2.upstream.Loader$LoadTask.run(Loader.java:381)
E/ExoPlayerImplInternal( 5024): 	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
E/ExoPlayerImplInternal( 5024): 	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
E/ExoPlayerImplInternal( 5024): 	at java.lang.Thread.run(Thread.java:764)
I/zygote  ( 5024): Do full code cache collection, code=122KB, data=85KB
I/zygote  ( 5024): After code cache collection, code=90KB, data=51KB


```

**Comment by phuongphally** [comment]
Please help correct to get it work sir. 

Thanks

**Comment by boyan01** [comment]
i'm sorry to say that I don't have time to write this project now. i have got more important thing to do, please be patient.

**Comment by Night-X** [comment]
Fix it, please. I follow you.

**Comment by boyan01** [comment]
this weekend. I'll try to find out what's wrong.

这几天忙着面试,真的没时间.
